aiserver:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    host: ${IPADDR}
    host: localhost
    port: 3306
    database: ai_application
    username: root
    password: 123456
  ai:
    api-key: ${BAILIAN_API_KEY}
  file:
    upload:
      path: D:\dev\upload\ # physical path
      url-prefix: /resources/images/ # url prefix
    gallery:
      path: D:\dev\collection\ # physical path
      url-prefix: /resources/collections/ # url prefix
