spring:
  application:
    name: ai-server
  profiles:
    active: dev
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${aiserver.ai.api-key}
      chat:
        options:
          model: qwen3-max-preview
          temperature: 0.9
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:schema-@@platform@@.sql
            platform: mysql
  datasource:
    driver-class-name: ${aiserver.datasource.driver-class-name}
    url: jdbc:mysql://${aiserver.datasource.host}:${aiserver.datasource.port}/${aiserver.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${aiserver.datasource.username}
    password: ${aiserver.datasource.password}
aiserver:
  jwt:
    secret-key: 72321474fd3a11ffbd1e88a6f35cd51058a4effe00940828b2c7ecb87cae14b5
    ttl: 259200000 # 3 days
    token-name: Authorization
logging:
  level:
#    org.springframework.ai.chat.client.advisor: debug
    xyz.qiquqiu.aiserver: debug
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
file:
  upload:
    path: ${aiserver.file.upload.path}
    url-prefix: ${aiserver.file.upload.url-prefix}
  gallery:
    path: ${aiserver.file.gallery.path}
    url-prefix: ${aiserver.file.gallery.url-prefix}
